# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curspace < Formula
  desc "Terminal-first project discovery and workspace launcher for Cursor IDE"
  homepage "https://github.com/frknikiz/curspace"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frknikiz/curspace/releases/download/v1.0.1/curspace_1.0.1_darwin_amd64.tar.gz"
      sha256 "6f0a9139c94357416e1465a9ba3dde45ab2a9a06ad6f5012bdf725c1c88a3332"

      define_method(:install) do
        bin.install "curspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frknikiz/curspace/releases/download/v1.0.1/curspace_1.0.1_darwin_arm64.tar.gz"
      sha256 "dc319d03b1dfee3d4e75946962d0a750e826b689c024ca86767e80a494388820"

      define_method(:install) do
        bin.install "curspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frknikiz/curspace/releases/download/v1.0.1/curspace_1.0.1_linux_amd64.tar.gz"
      sha256 "2f10ad5e286f65d9eacb4d3f4462486a8db39cc75b40ba1153666663161916a1"
      define_method(:install) do
        bin.install "curspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frknikiz/curspace/releases/download/v1.0.1/curspace_1.0.1_linux_arm64.tar.gz"
      sha256 "c8fbe1cbb516d31f75ba6eee3bd4071ffe22f3cb9090661887a9568f5df31da6"
      define_method(:install) do
        bin.install "curspace"
      end
    end
  end
end
